from typing import Any, Dict, Optional

WORDING : Dict[str, Any] =\
{
	'conda_not_activated': 'Conda não está ativado',
	'python_not_supported': 'Versão do Python não é suportada, atualize para {version} ou superior',
	'curl_not_installed': 'CURL não está instalado',
	'ffmpeg_not_installed': 'FFMpeg não está instalado',
	'creating_temp': 'Criando recursos temporários',
	'extracting_frames': 'Extraindo quadros com resolução de {resolution} e {fps} quadros por segundo',
	'extracting_frames_succeed': 'Extração de quadros concluída com sucesso',
	'extracting_frames_failed': 'Falha na extração de quadros',
	'analysing': 'Analisando',
	'extracting': 'Extraindo',
	'streaming': 'Transmitindo',
	'processing': 'Processando',
	'merging': 'Mesclando',
	'downloading': 'Baixando',
	'temp_frames_not_found': 'Quadros temporários não encontrados',
	'copying_image': 'Copiando imagem com resolução de {resolution}',
	'copying_image_succeed': 'Cópia da imagem concluída com sucesso',
	'copying_image_failed': 'Falha na cópia da imagem',
	'finalizing_image': 'Finalizando imagem com resolução de {resolution}',
	'finalizing_image_succeed': 'Finalização da imagem concluída com sucesso',
	'finalizing_image_skipped': 'Finalização da imagem ignorada',
	'merging_video': 'Mesclando vídeo com resolução de {resolution} e {fps} quadros por segundo',
	'merging_video_succeed': 'Mesclagem de vídeo concluída com sucesso',
	'merging_video_failed': 'Falha na mesclagem de vídeo',
	'skipping_audio': 'Ignorando áudio',
	'replacing_audio_succeed': 'Substituição de áudio concluída com sucesso',
	'replacing_audio_skipped': 'Substituição de áudio ignorada',
	'restoring_audio_succeed': 'Restauração de áudio concluída com sucesso',
	'restoring_audio_skipped': 'Restauração de áudio ignorada',
	'clearing_temp': 'Limpando recursos temporários',
	'processing_stopped': 'Processamento interrompido',
	'processing_image_succeed': 'Processamento para imagem concluído com sucesso em {seconds} segundos',
	'processing_image_failed': 'Falha no processamento para imagem',
	'processing_video_succeed': 'Processamento para vídeo concluído com sucesso em {seconds} segundos',
	'processing_video_failed': 'Falha no processamento para vídeo',
	'choose_image_source': 'Escolha uma imagem como fonte',
	'choose_audio_source': 'Escolha um áudio como fonte',
	'choose_video_target': 'Escolha um vídeo como destino',
	'choose_image_or_video_target': 'Escolha uma imagem ou vídeo como destino',
	'specify_image_or_video_output': 'Especifique a saída de imagem ou vídeo em um diretório',
	'match_target_and_output_extension': 'Combine a extensão do destino e da saída',
	'no_source_face_detected': 'Nenhum rosto detectado na fonte',
	'processor_not_loaded': 'Processador {processor} não pôde ser carregado',
	'processor_not_implemented': 'Processador {processor} não implementado corretamente',
	'ui_layout_not_loaded': 'Layout de UI {ui_layout} não pôde ser carregado',
	'ui_layout_not_implemented': 'Layout de UI {ui_layout} não implementado corretamente',
	'stream_not_loaded': 'Fluxo {stream_mode} não pôde ser carregado',
	'stream_not_supported': 'Fluxo não suportado',
	'job_created': 'Tarefa {job_id} criada',
	'job_not_created': 'Tarefa {job_id} não criada',
	'job_submitted': 'Tarefa {job_id} enviada',
	'job_not_submitted': 'Tarefa {job_id} não enviada',
	'job_all_submitted': 'Tarefas enviadas',
	'job_all_not_submitted': 'Tarefas não enviadas',
	'job_deleted': 'Tarefa {job_id} excluída',
	'job_not_deleted': 'Tarefa {job_id} não excluída',
	'job_all_deleted': 'Tarefas excluídas',
	'job_all_not_deleted': 'Tarefas não excluídas',
	'job_step_added': 'Etapa adicionada à tarefa {job_id}',
	'job_step_not_added': 'Etapa não adicionada à tarefa {job_id}',
	'job_remix_step_added': 'Etapa {step_index} remixada da tarefa {job_id}',
	'job_remix_step_not_added': 'Etapa {step_index} não remixada da tarefa {job_id}',
	'job_step_inserted': 'Etapa {step_index} inserida na tarefa {job_id}',
	'job_step_not_inserted': 'Etapa {step_index} não inserida na tarefa {job_id}',
	'job_step_removed': 'Etapa {step_index} removida da tarefa {job_id}',
	'job_step_not_removed': 'Etapa {step_index} não removida da tarefa {job_id}',
	'running_job': 'Executando tarefa na fila {job_id}',
	'running_jobs': 'Executando todas as tarefas na fila',
	'retrying_job': 'Tentando novamente a tarefa com falha {job_id}',
	'retrying_jobs': 'Tentando novamente todas as tarefas com falha',
	'processing_job_succeed': 'Processamento da tarefa {job_id} concluído com sucesso',
	'processing_jobs_succeed': 'Processamento de todas as tarefas concluído com sucesso',
	'processing_job_failed': 'Falha no processamento da tarefa {job_id}',
	'processing_jobs_failed': 'Falha no processamento de todas as tarefas',
	'processing_step': 'Processando etapa {step_current} de {step_total}',
	'validating_hash_succeed': 'Validação do hash para {hash_file_name} concluída com sucesso',
	'validating_hash_failed': 'Falha na validação do hash para {hash_file_name}',
	'validating_source_succeed': 'Validação da fonte para {source_file_name} concluída com sucesso',
	'validating_source_failed': 'Falha na validação da fonte para {source_file_name}',
	'deleting_corrupt_source': 'Excluindo fonte corrompida para {source_file_name}',
	'time_ago_now': 'agora mesmo',
	'time_ago_minutes': 'há {minutes} minutos',
	'time_ago_hours': 'há {hours} horas e {minutes} minutos',
	'time_ago_days': 'há {days} dias, {hours} horas e {minutes} minutos',
	'point': '.',
	'comma': ',',
	'colon': ':',
	'question_mark': '?',
	'exclamation_mark': '!',
	'help': 
	{
		# Installer
		'install_dependency': 'escolha a variante de {dependency} para instalar',
		'skip_conda': 'pule a verificação do ambiente conda',
		
		# Paths
		'config_path': 'escolha o arquivo de configuração para sobrescrever os padrões',
		'temp_path': 'especifique o diretório para os recursos temporários',
		'jobs_path': 'especifique o diretório para armazenar os trabalhos',
		'source_paths': 'escolha os caminhos da imagem ou áudio',
		'target_path': 'escolha o caminho da imagem ou vídeo',
		'output_path': 'especifique a imagem ou vídeo dentro de um diretório',
		
		# Patterns
		'source_pattern': 'escolha o padrão da imagem ou áudio',
		'target_pattern': 'escolha o padrão da imagem ou vídeo',
		'output_pattern': 'especifique o padrão da imagem ou vídeo',
		
		# Face Detector
		'face_detector_model': 'escolha o modelo responsável por detectar as faces',
		'face_detector_size': 'especifique o tamanho do quadro fornecido ao detector de faces',
		'face_detector_angles': 'especifique os ângulos para rotacionar o quadro antes de detectar as faces',
		'face_detector_score': 'filtre as faces detectadas com base na pontuação de confiança',
		
		# Face Landmarker
		'face_landmarker_model': 'escolha o modelo responsável por detectar os marcos faciais',
		'face_landmarker_score': 'filtre os marcos faciais detectados com base na pontuação de confiança',
		
		# Face Selector
		'face_selector_mode': 'use o rastreamento baseado em referência ou correspondência simples',
		'face_selector_order': 'especifique a ordem das faces detectadas',
		'face_selector_age_start': 'filtre as faces detectadas com base na idade inicial',
		'face_selector_age_end': 'filtre as faces detectadas com base na idade final',
		'face_selector_gender': 'filtre as faces detectadas com base no gênero',
		'face_selector_race': 'filtre as faces detectadas com base na raça',
		'reference_face_position': 'especifique a posição usada para criar a face de referência',
		'reference_face_distance': 'especifique a similaridade entre a face de referência e a face alvo',
		'reference_frame_number': 'especifique o quadro usado para criar a face de referência',
		
		# Face Masker
		'face_occluder_model': 'escolha o modelo responsável pela máscara de oclusão',
		'face_parser_model': 'escolha o modelo responsável pela máscara de região',
		'face_mask_types': 'misture e combine diferentes tipos de máscaras faciais (escolhas: {choices})',
		'face_mask_blur': 'especifique o grau de desfoque aplicado à máscara de caixa',
		'face_mask_padding': 'aplique o preenchimento superior, direito, inferior e esquerdo à máscara de caixa',
		'face_mask_regions': 'escolha as características faciais usadas para a máscara de região (escolhas: {choices})',
		
		# Frame Extraction
		'trim_frame_start': 'especifique o quadro de início do vídeo alvo',
		'trim_frame_end': 'especifique o quadro de fim do vídeo alvo',
		'temp_frame_format': 'especifique o formato dos recursos temporários',
		'keep_temp': 'mantenha os recursos temporários após o processamento',
		
		# Output Creation
		'output_image_quality': 'especifique a qualidade da imagem, o que se traduz no fator de compressão',
		'output_image_resolution': 'especifique a resolução de saída da imagem com base na imagem alvo',
		'output_audio_encoder': 'especifique o codificador usado para a saída de áudio',
		'output_video_encoder': 'especifique o codificador usado para a saída de vídeo',
		'output_video_preset': 'balanceie o processamento rápido de vídeo e o tamanho do arquivo',
		'output_video_quality': 'especifique a qualidade do vídeo, o que se traduz no fator de compressão',
		'output_video_resolution': 'especifique a resolução de saída do vídeo com base no vídeo alvo',
		'output_video_fps': 'especifique os quadros por segundo do vídeo de saída com base no vídeo alvo',
		'skip_audio': 'omita o áudio do vídeo alvo',
		
		# Processors
		'processors': 'carregue um ou vários processadores (escolhas: {choices}, ...)',
		'age_modifier_model': 'escolha o modelo responsável por envelhecer a face',
		'age_modifier_direction': 'especifique a direção na qual a idade deve ser modificada',
		'deep_swapper_model': 'escolha o modelo responsável por trocar as faces',
		'deep_swapper_morph': 'morfose entre a face de origem e as faces alvo',
		'expression_restorer_model': 'escolha o modelo responsável por restaurar a expressão',
		'expression_restorer_factor': 'fator de restauração da expressão da face alvo',
		'face_debugger_items': 'carregue um ou vários processadores (escolhas: {choices})',
		'face_editor_model': 'escolha o modelo responsável por editar a face',
		'face_editor_eyebrow_direction': 'especifique a direção das sobrancelhas',
		'face_editor_eye_gaze_horizontal': 'especifique o olhar horizontal dos olhos',
		'face_editor_eye_gaze_vertical': 'especifique o olhar vertical dos olhos',
		'face_editor_eye_open_ratio': 'especifique o grau de abertura dos olhos',
		'face_editor_lip_open_ratio': 'especifique o grau de abertura dos lábios',
		'face_editor_mouth_grim': 'especifique o franzido da boca',
		'face_editor_mouth_pout': 'especifique o movimento de beicinho da boca',
		'face_editor_mouth_purse': 'especifique o movimento de apertar os lábios',
		'face_editor_mouth_smile': 'especifique o sorriso da boca',
		'face_editor_mouth_position_horizontal': 'especifique a posição horizontal da boca',
		'face_editor_mouth_position_vertical': 'especifique a posição vertical da boca',
		'face_editor_head_pitch': 'especifique o ângulo de inclinação da cabeça',
		'face_editor_head_yaw': 'especifique o ângulo de rotação da cabeça',
		'face_editor_head_roll': 'especifique o ângulo de rotação lateral da cabeça',
		'face_enhancer_model': 'escolha o modelo responsável por aprimorar a face',
		'face_enhancer_blend': 'misture o aprimoramento com a face anterior',
		'face_enhancer_weight': 'especifique o grau de peso aplicado à face',
		'face_swapper_model': 'escolha o modelo responsável por trocar a face',
		'face_swapper_pixel_boost': 'escolha a resolução de aumento de pixels para o trocador de faces',
		'frame_colorizer_model': 'escolha o modelo responsável por colorir o quadro',
		'frame_colorizer_size': 'especifique o tamanho do quadro fornecido ao colorizador de quadro',
		'frame_colorizer_blend': 'misture o quadro colorido com o quadro anterior',
		'frame_enhancer_model': 'escolha o modelo responsável por aprimorar o quadro',
		'frame_enhancer_blend': 'misture o aprimoramento com o quadro anterior',
		'lip_syncer_model': 'escolha o modelo responsável por sincronizar os lábios',
		
		# UIs
		'open_browser': 'abra o navegador assim que o programa estiver pronto',
		'ui_layouts': 'lance um ou vários layouts de UI (escolhas: {choices}, ...)',
		'ui_workflow': 'escolha o fluxo de trabalho da UI',
		
		# Execution
		'execution_device_id': 'especifique o dispositivo usado para o processamento',
		'execution_providers': 'inferência usando diferentes provedores (escolhas: {choices}, ...)',
		'execution_thread_count': 'especifique o número de threads paralelas durante o processamento',
		'execution_queue_count': 'especifique o número de quadros que cada thread está processando',
		
		# Download
		'download_providers': 'faça o download usando diferentes provedores (escolhas: {choices}, ...)',
		'download_scope': 'especifique o escopo do download',
		
		# Memory
		'video_memory_strategy': 'balanceie o processamento rápido e o baixo uso de VRAM',
		'system_memory_limit': 'limite a RAM disponível para uso durante o processamento',
		
		# Misc
		'log_level': 'ajuste a severidade das mensagens exibidas no terminal',
		
		# Run
		'run': 'execute o programa',
		'headless_run': 'execute o programa em modo sem cabeça',
		'batch_run': 'execute o programa em modo em lote',
		'force_download': 'force o download automático e saia',
		
		# Jobs
		'job_id': 'especifique o ID do trabalho',
		'job_status': 'especifique o status do trabalho',
		'step_index': 'especifique o índice do passo',
		# Job Manager
		'job_list': 'listar trabalhos por status',
		'job_create': 'criar um trabalho rascunho',
		'job_submit': 'enviar um trabalho rascunho para ser um trabalho na fila',
		'job_submit_all': 'enviar todos os trabalhos rascunhos para serem trabalhos na fila',
		'job_delete': 'excluir um trabalho rascunho, na fila, falhado ou concluído',
		'job_delete_all': 'excluir todos os trabalhos rascunhos, na fila, falhados e concluídos',
		'job_add_step': 'adicionar um passo a um trabalho rascunho',
		'job_remix_step': 'remixar um passo anterior de um trabalho rascunho',
		'job_insert_step': 'inserir um passo a um trabalho rascunho',
		'job_remove_step': 'remover um passo de um trabalho rascunho',
		
		# Job Runner
		'job_run': 'executar um trabalho na fila',
		'job_run_all': 'executar todos os trabalhos na fila',
		'job_retry': 'tentar novamente um trabalho falhado',
		'job_retry_all': 'tentar novamente todos os trabalhos falhados'
	},
	'about':
	{
		'become_a_member': 'become a member',
		'join_our_community': 'join our community',
		'read_the_documentation': 'read the documentation'
	},
	'uis':
	{
		'age_modifier_direction_slider': 'DIREÇÃO DO MODIFICADOR DE IDADE',
		'age_modifier_model_dropdown': 'MODELO DO MODIFICADOR DE IDADE',
		'apply_button': 'APLICAR',
		'benchmark_cycles_slider': 'CICLOS DE AVALIAÇÃO',
		'benchmark_runs_checkbox_group': 'EXECUÇÕES DE AVALIAÇÃO',
		'clear_button': 'LIMPAR',
		'common_options_checkbox_group': 'OPÇÕES',
		'download_providers_checkbox_group': 'PROVEDORES DE DOWNLOAD',
		'deep_swapper_model_dropdown': 'MODELO DO TROCADOR DE FACES',
		'deep_swapper_morph_slider': 'MORFOSE DO TROCADOR DE FACES',
		'execution_providers_checkbox_group': 'PROVEDORES DE EXECUÇÃO',
		'execution_queue_count_slider': 'CONTAGEM DE FILA DE EXECUÇÃO',
		'execution_thread_count_slider': 'CONTAGEM DE THREADS DE EXECUÇÃO',
		'expression_restorer_factor_slider': 'FATOR DE RESTAURAÇÃO DE EXPRESSÃO',
		'expression_restorer_model_dropdown': 'MODELO DE RESTAURAÇÃO DE EXPRESSÃO',
		'face_debugger_items_checkbox_group': 'ITENS DO DEBUGADOR DE ROSTO',
		'face_detector_angles_checkbox_group': 'ÂNGULOS DO DETECTOR DE ROSTO',
		'face_detector_model_dropdown': 'MODELO DO DETECTOR DE ROSTO',
		'face_detector_score_slider': 'PONTUAÇÃO DO DETECTOR DE ROSTO',
		'face_detector_size_dropdown': 'TAMANHO DO DETECTOR DE ROSTO',
		'face_editor_eyebrow_direction_slider': 'DIREÇÃO DAS SOBRANCELHAS NO EDITOR DE ROSTO',
		'face_editor_eye_gaze_horizontal_slider': 'OLHAR HORIZONTAL NO EDITOR DE ROSTO',
		'face_editor_eye_gaze_vertical_slider': 'OLHAR VERTICAL NO EDITOR DE ROSTO',
		'face_editor_eye_open_ratio_slider': 'PROPORÇÃO DE ABERTURA DOS OLHOS NO EDITOR DE ROSTO',
		'face_editor_head_pitch_slider': 'INCLINAÇÃO DA CABEÇA NO EDITOR DE ROSTO',
		'face_editor_head_roll_slider': 'ROTAÇÃO DA CABEÇA NO EDITOR DE ROSTO',
		'face_editor_head_yaw_slider': 'ROTACIONAMENTO DA CABEÇA NO EDITOR DE ROSTO',
		'face_editor_lip_open_ratio_slider': 'PROPORÇÃO DE ABERTURA DOS LÁBIOS NO EDITOR DE ROSTO',
		'face_editor_model_dropdown': 'MODELO DO EDITOR DE ROSTO',
		'face_editor_mouth_grim_slider': 'FRANZIDO DA BOCA NO EDITOR DE ROSTO',
		'face_editor_mouth_position_horizontal_slider': 'POSIÇÃO HORIZONTAL DA BOCA NO EDITOR DE ROSTO',
		'face_editor_mouth_position_vertical_slider': 'POSIÇÃO VERTICAL DA BOCA NO EDITOR DE ROSTO',
		'face_editor_mouth_pout_slider': 'MOVIMENTO DE BEICINHO NA BOCA NO EDITOR DE ROSTO',
		'face_editor_mouth_purse_slider': 'MOVIMENTO DE APERTAR A BOCA NO EDITOR DE ROSTO',
		'face_editor_mouth_smile_slider': 'SORRISO DA BOCA NO EDITOR DE ROSTO',
		'face_enhancer_blend_slider': 'MISTURA DE APERFEIÇOAMENTO DE ROSTO',
		'face_enhancer_model_dropdown': 'MODELO DE APERFEIÇOAMENTO DE ROSTO',
		'face_enhancer_weight_slider': 'PESO DE APERFEIÇOAMENTO DE ROSTO',
		'face_landmarker_model_dropdown': 'MODELO DO MARCADOR DE ROSTO',
		'face_landmarker_score_slider': 'PONTUAÇÃO DO MARCADOR DE ROSTO',
		'face_mask_blur_slider': 'DESFOQUE DA MÁSCARA DE ROSTO',
		'face_mask_padding_bottom_slider': 'PREENCHEMENTO INFERIOR DA MÁSCARA DE ROSTO',
		'face_mask_padding_left_slider': 'PREENCHEMENTO ESQUERDO DA MÁSCARA DE ROSTO',
		'face_mask_padding_right_slider': 'PREENCHEMENTO DIREITO DA MÁSCARA DE ROSTO',
		'face_mask_padding_top_slider': 'PREENCHEMENTO SUPERIOR DA MÁSCARA DE ROSTO',
		'face_mask_regions_checkbox_group': 'REGIÕES DA MÁSCARA DE ROSTO',
		'face_mask_types_checkbox_group': 'TIPOS DE MÁSCARA DE ROSTO',
		'face_selector_age_range_slider': 'FAIXA ETÁRIA DO SELECIONADOR DE ROSTO',
		'face_selector_gender_dropdown': 'GÊNERO DO SELECIONADOR DE ROSTO',
		'face_selector_mode_dropdown': 'MODO DO SELECIONADOR DE ROSTO',
		'face_selector_order_dropdown': 'ORDEM DO SELECIONADOR DE ROSTO',
		'face_selector_race_dropdown': 'RAÇA DO SELECIONADOR DE ROSTO',
		'face_swapper_model_dropdown': 'MODELO DO TROCADOR DE ROSTO',
		'face_swapper_pixel_boost_dropdown': 'AUMENTO DE PIXEIS DO TROCADOR DE ROSTO',
		'face_occluder_model_dropdown': 'MODELO DE OCLUSÃO DE ROSTO',
		'face_parser_model_dropdown': 'MODELO DE ANÁLISE DE ROSTO',
		'frame_colorizer_blend_slider': 'MISTURA DO COLORIDOR DE QUADRO',
		'frame_colorizer_model_dropdown': 'MODELO DO COLORIDOR DE QUADRO',
		'frame_colorizer_size_dropdown': 'TAMANHO DO COLORIDOR DE QUADRO',
		'frame_enhancer_blend_slider': 'MISTURA DO APERFEIÇOADOR DE QUADRO',
		'frame_enhancer_model_dropdown': 'MODELO DO APERFEIÇOADOR DE QUADRO',
		'job_list_status_checkbox_group': 'STATUS DO TRABALHO',
		'job_manager_job_action_dropdown': 'AÇÃO DO TRABALHO',
		'job_manager_job_id_dropdown': 'ID DO TRABALHO',
		'job_manager_step_index_dropdown': 'ÍNDICE DO PASSO',
		'job_runner_job_action_dropdown': 'AÇÃO DO TRABALHO',
		'job_runner_job_id_dropdown': 'ID DO TRABALHO',
		'lip_syncer_model_dropdown': 'MODELO DE SINCRONIZAÇÃO DE LÁBIOS',
		'log_level_dropdown': 'NÍVEL DE LOG',
		'output_audio_encoder_dropdown': 'CODIFICADOR DE ÁUDIO DE SAÍDA',
		'output_image_or_video': 'SAÍDA',
		'output_image_quality_slider': 'QUALIDADE DA IMAGEM DE SAÍDA',
		'output_image_resolution_dropdown': 'RESOLUÇÃO DA IMAGEM DE SAÍDA',
		'output_path_textbox': 'CAMINHO DE SAÍDA',
		'output_video_encoder_dropdown': 'CODIFICADOR DE VÍDEO DE SAÍDA',
		'output_video_fps_slider': 'FPS DE VÍDEO DE SAÍDA',
		'output_video_preset_dropdown': 'PREDEFINIÇÃO DE VÍDEO DE SAÍDA',
		'output_video_quality_slider': 'QUALIDADE DO VÍDEO DE SAÍDA',
		'output_video_resolution_dropdown': 'RESOLUÇÃO DO VÍDEO DE SAÍDA',
		'preview_frame_slider': 'SLIDER DE QUADRO DE PRÉ-VISUALIZAÇÃO',
		'preview_image': 'PRÉ-visualização',
		'processors_checkbox_group': 'PROCESSADORES',
		'reference_face_distance_slider': 'DISTÂNCIA DA FACE DE REFERÊNCIA',
		'reference_face_gallery': 'GALERIA DE FACE DE REFERÊNCIA',
		'refresh_button': 'ATUALIZAR',
		'source_file': 'ARQUIVO DE ORIGEM',
		'start_button': 'INICIAR',
		'stop_button': 'PARAR',
		'system_memory_limit_slider': 'LIMITE DE MEMÓRIA DO SISTEMA',
		'target_file': 'ARQUIVO DE DESTINO',
		'temp_frame_format_dropdown': 'FORMATO DO QUADRO TEMPORÁRIO',
		'terminal_textbox': 'CAIXA DE TEXTO DO TERMINAL',
		'trim_frame_slider': 'SLIDER DE CORTE DE QUADRO',
		'ui_workflow': 'FLUXO DE TRABALHO DA UI',
		'video_memory_strategy_dropdown': 'ESTRATÉGIA DE MEMÓRIA DE VÍDEO',
		'webcam_fps_slider': 'FPS DA WEBCAM',
		'webcam_image': 'IMAGEM DA WEBCAM',
		'webcam_device_id_dropdown': 'ID DO DISPOSITIVO DA WEBCAM',
		'webcam_mode_radio': 'MODO DA WEBCAM',
		'webcam_resolution_dropdown': 'RESOLUÇÃO DA WEBCAM'
	}
}


def get(key : str) -> Optional[str]:
	if '.' in key:
		section, name = key.split('.')
		if section in WORDING and name in WORDING.get(section):
			return WORDING.get(section).get(name)
	if key in WORDING:
		return WORDING.get(key)
	return None
